fira6_joint_publisher:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Position Controllers ---------------------------------------
fira_wl_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: base_l_wheel_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}

fira_wr_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: base_r_wheel_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}


fira_wb_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: base_back_wheel_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}
