global_frame: odom
rolling_window: true

plugins:
  - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
  - {name: gridlayer,        type: "grid_layer_namespace::GridLayer"}
  - {name: inflation_layer,        type: "costmap_2d::InflationLayer"}
